version: '3.3'
services:
  jaeger:
    ports:
     - "5775:5775/udp"
     - "6831:6831/udp"
     - "6832:6832/udp" # default UDP reporter port
     - "16686:16686"   # UI port
     - "14268:14268"
    image: jaegertracing/all-in-one:latest
  api-gateway:
    depends_on:
       - user-api
    build: services/api-gateway
    restart: on-failure
    ports:
      - "3000:3000" #entrypoint
    environment:
      JAEGER_HOST: jaeger
      USER_API_SERVICE_HOST: user-api
      USER_API_SERVICE_PORT: 3000
    volumes: 
      - ./services/api-gateway/api:/wdir/api
      # map local './services/api-gateway/api' folder to container '/wdir/api'
    command: sh -c "npm run dev"
  user-api:
    build: services/user-api
    restart: on-failure
    ports:
     - "3001:3000" # exposed for debugging
    environment:
      JAEGER_HOST: jaeger
    volumes: 
      - ./services/user-api/api:/wdir/api
    command: sh -c "npm run dev"

